import { ModelPricing, PricingUnit } from './types';

export const ANTHROPIC_PRICING: ModelPricing[] = [
  {
    modelId: 'claude-3-haiku-20240307',
    modelName: 'Claude 3 Haiku',
    provider: 'Anthropic',
    inputPrice: 0.25,
    outputPrice: 1.25,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Haiku - fast and cost-effective',
  },
  {
    modelId: 'claude-3-sonnet-20240229',
    modelName: 'Claude 3 Sonnet',
    provider: 'Anthropic',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Sonnet - balanced performance and reasoning',
  },
  {
    modelId: 'claude-3-opus-20240229',
    modelName: 'Claude 3 Opus',
    provider: 'Anthropic',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Opus - most capable model',
  },
  // Claude 4 family — Messages API model strings (registry keys: anthropic:<modelId>)
  {
    modelId: 'claude-sonnet-4-20250514',
    modelName: 'Claude Sonnet 4',
    provider: 'Anthropic',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4 — aligned with Bedrock Sonnet 4 pricing',
  },
  {
    modelId: 'claude-sonnet-4-5-20250929',
    modelName: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding', 'agents'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4.5',
  },
  {
    modelId: 'claude-sonnet-4-6',
    modelName: 'Claude Sonnet 4.6',
    provider: 'Anthropic',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4.6',
  },
  {
    modelId: 'claude-opus-4-20250514',
    modelName: 'Claude Opus 4',
    provider: 'Anthropic',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4',
  },
  {
    modelId: 'claude-opus-4-1-20250805',
    modelName: 'Claude Opus 4.1',
    provider: 'Anthropic',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4.1',
  },
  {
    modelId: 'claude-opus-4-5-20250514',
    modelName: 'Claude Opus 4.5',
    provider: 'Anthropic',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: false,
    notes: 'Claude Opus 4.5',
  },
  {
    modelId: 'claude-opus-4-6',
    modelName: 'Claude Opus 4.6',
    provider: 'Anthropic',
    inputPrice: 5.0,
    outputPrice: 25.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex', 'vision', 'agents'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4.6 — Messages API; verify id/snapshot on docs.anthropic.com',
  },
  {
    modelId: 'claude-opus-4-7',
    modelName: 'Claude Opus 4.7',
    provider: 'Anthropic',
    inputPrice: 5.0,
    outputPrice: 25.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex', 'vision', 'agents'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4.7 — same list pricing as 4.6 per Anthropic (Apr 2026)',
  },
];
