import { ModelPricing, PricingUnit } from './types';

export const ANTHROPIC_PRICING: ModelPricing[] = [
  {
    modelId: 'claude-3-haiku-20240307',
    modelName: 'Claude 3 Haiku',
    provider: 'Anthropic',
    inputPrice: 0.25,
    outputPrice: 1.25,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Haiku - fast and cost-effective',
  },
  {
    modelId: 'claude-3-sonnet-20240229',
    modelName: 'Claude 3 Sonnet',
    provider: 'Anthropic',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Sonnet - balanced performance and reasoning',
  },
  {
    modelId: 'claude-3-opus-20240229',
    modelName: 'Claude 3 Opus',
    provider: 'Anthropic',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3 Opus - most capable model',
  },
];
