import { ModelPricing, PricingUnit } from './types';

export const AWS_BEDROCK_PRICING: ModelPricing[] = [
    // Amazon Nova Models
    {
        modelId: 'amazon.nova-pro-v1:0',
        modelName: 'Nova Pro',
        provider: 'AWS Bedrock',
        inputPrice: 0.80,
        outputPrice: 3.20,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['text', 'vision'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Pro - Best value multimodal model'
    },
    {
        modelId: 'amazon.nova-lite-v1:0',
        modelName: 'Nova Lite',
        provider: 'AWS Bedrock',
        inputPrice: 0.06,
        outputPrice: 0.24,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['text', 'fast'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Lite - Fast and efficient'
    },
    {
        modelId: 'amazon.nova-micro-v1:0',
        modelName: 'Nova Micro',
        provider: 'AWS Bedrock',
        inputPrice: 0.035,
        outputPrice: 0.14,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'fast'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Micro - Ultra fast for simple tasks'
    },
    
    // AI21 Labs Models
    {
        modelId: 'ai21.jamba-1-5-large-v1:0',
        modelName: 'Jamba',
        provider: 'AWS Bedrock',
        inputPrice: 2.0,
        outputPrice: 8.0,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 256000,
        capabilities: ['text', 'long-context'],
        category: 'text',
        isLatest: true,
        notes: 'AI21 Labs Jamba 1.5 Large - advanced AI model for text generation and chat'
    },
    {
        modelId: 'ai21.jamba-1-5-mini-v1:0',
        modelName: 'Jamba',
        provider: 'AWS Bedrock',
        inputPrice: 0.2,
        outputPrice: 0.4,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 256000,
        capabilities: ['text', 'long-context', 'efficient'],
        category: 'text',
        isLatest: true,
        notes: 'AI21 Labs Jamba 1.5 Mini - advanced AI model for text generation and chat'
    },
    {
        modelId: 'ai21.jamba-instruct-v1:0',
        modelName: 'Jamba Instruct',
        provider: 'AWS Bedrock',
        inputPrice: 0.5,
        outputPrice: 0.7,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 256000,
        capabilities: ['text', 'instruct', 'long-context'],
        category: 'text',
        isLatest: true,
        notes: 'AI21 Labs Jamba-Instruct - hybrid architecture for long context tasks'
    },

    // Amazon Nova Models
    {
        modelId: 'amazon.nova-micro-v1:0',
        modelName: 'Amazon Nova Micro',
        provider: 'AWS Bedrock',
        inputPrice: 0.035,
        outputPrice: 0.14,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'efficient', 'cache-read'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Micro with cache read support ($0.00875/1M cache read tokens)'
    },
    {
        modelId: 'amazon.nova-lite-v1:0',
        modelName: 'Amazon Nova Lite',
        provider: 'AWS Bedrock',
        inputPrice: 0.06,
        outputPrice: 0.24,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['text', 'multimodal', 'cache-read'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Lite with cache read support ($0.015/1M cache read tokens)'
    },
    {
        modelId: 'amazon.nova-pro-v1:0',
        modelName: 'Amazon Nova Pro',
        provider: 'AWS Bedrock',
        inputPrice: 0.8,
        outputPrice: 3.2,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['text', 'multimodal', 'cache-read'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Pro with cache read support ($0.2/1M cache read tokens)'
    },
    {
        modelId: 'amazon.nova-premier-v1:0',
        modelName: 'Nova Premier',
        provider: 'AWS Bedrock',
        inputPrice: 2.5,
        outputPrice: 12.5,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['text', 'multimodal', 'advanced-reasoning'],
        category: 'text',
        isLatest: true,
        notes: 'Amazon Nova Premier - advanced AI model for text generation and chat with cache read support'
    },
    {
        modelId: 'amazon.nova-canvas-v1:0',
        modelName: 'Nova Canvas',
        provider: 'AWS Bedrock',
        inputPrice: 0.04,
        outputPrice: 0.04,
        unit: PricingUnit.PER_REQUEST,
        contextWindow: 0,
        capabilities: ['image-generation'],
        category: 'image',
        isLatest: true,
        notes: 'Amazon Nova Canvas via AWS Bedrock - image generation model'
    },
    {
        modelId: 'amazon.nova-reel-v1:0',
        modelName: 'Nova Reel',
        provider: 'AWS Bedrock',
        inputPrice: 0.08,
        outputPrice: 0.08,
        unit: PricingUnit.PER_REQUEST,
        contextWindow: 0,
        capabilities: ['video-generation'],
        category: 'video',
        isLatest: true,
        notes: 'Amazon Nova Reel via AWS Bedrock - video generation model'
    },
    {
        modelId: 'amazon.nova-sonic-v1:0',
        modelName: 'Amazon Nova Sonic',
        provider: 'AWS Bedrock',
        inputPrice: 3.4,
        outputPrice: 13.6,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 300000,
        capabilities: ['speech', 'multimodal', 'native-audio'],
        category: 'audio',
        isLatest: true,
        notes: 'Amazon Nova Sonic via AWS Bedrock. Text input: $0.06, Text output: $0.24'
    },

    // Amazon Titan Models
    {
        modelId: 'amazon.titan-text-express-v1',
        modelName: 'Titan Text Express',
        provider: 'AWS Bedrock',
        inputPrice: 0.8,
        outputPrice: 1.6,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 8000,
        capabilities: ['text'],
        category: 'text',
        isLatest: true,
        notes: "Amazon Titan Text Express - advanced AI model for text generation and chat"
    },
    {
        modelId: 'amazon.titan-text-lite-v1',
        modelName: 'Amazon Titan Text Lite',
        provider: 'AWS Bedrock',
        inputPrice: 0.3,
        outputPrice: 0.4,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 4000,
        capabilities: ['text'],
        category: 'text',
        isLatest: true,
        notes: 'Lightweight Amazon Titan model via Bedrock'
    },
    {
        modelId: 'amazon.titan-embed-text-v2:0',
        modelName: 'Titan Embeddings V2',
        provider: 'AWS Bedrock',
        inputPrice: 0.02,
        outputPrice: 0.02,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 8192,
        capabilities: ['embedding'],
        category: 'embedding',
        isLatest: true,
        notes: 'Amazon Titan Text Embeddings V2 - advanced AI model for text generation and chat'
    },

    // Anthropic Models on AWS Bedrock
    {
        modelId: 'anthropic.claude-sonnet-4-5-v1:0',
        modelName: 'Claude Sonnet 4.5',
        provider: 'AWS Bedrock',
        inputPrice: 3.00,
        outputPrice: 15.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'extended-thinking', 'multilingual'],
        category: 'text',
        isLatest: true,
        notes: 'Claude Sonnet 4.5 on AWS Bedrock - latest Claude Sonnet model with enhanced capabilities and 1M context window support (beta)'
    },
    {
        modelId: 'anthropic.claude-haiku-4-5-v1:0',
        modelName: 'Claude Haiku 4.5',
        provider: 'AWS Bedrock',
        inputPrice: 1.00,
        outputPrice: 5.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'multilingual'],
        category: 'text',
        isLatest: true,
        notes: 'Claude Haiku 4.5 on AWS Bedrock - latest Claude Haiku model with improved performance'
    },
    {
        modelId: 'anthropic.claude-opus-4-1-20250805-v1:0',
        modelName: 'Claude 4 Opus',
        provider: 'AWS Bedrock',
        inputPrice: 15.00,
        outputPrice: 75.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'extended-thinking', 'multilingual'],
        category: 'text',
        isLatest: true,
        notes: 'Claude Opus 4.1 on AWS Bedrock - most powerful model for complex reasoning'
    },
    {
        modelId: 'anthropic.claude-opus-4-20250514-v1:0',
        modelName: 'Claude Opus 4',
        provider: 'AWS Bedrock',
        inputPrice: 15.00,
        outputPrice: 75.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'extended-thinking', 'multilingual'],
        category: 'text',
        isLatest: true,
        notes: 'Claude Opus 4 on AWS Bedrock - previous flagship model'
    },
    {
        modelId: 'anthropic.claude-sonnet-4-20250514-v1:0',
        modelName: 'Claude Sonnet 4',
        provider: 'AWS Bedrock',
        inputPrice: 3.00,
        outputPrice: 15.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'extended-thinking', 'multilingual'],
        category: 'text',
        isLatest: true,
        notes: 'Claude Sonnet 4 on AWS Bedrock - high-performance model with exceptional reasoning'
    },
    {
        modelId: 'anthropic.claude-3-7-sonnet-20250219-v1:0',
        modelName: 'Claude Sonnet 3.7',
        provider: 'AWS Bedrock',
        inputPrice: 3.00,
        outputPrice: 15.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'extended-thinking', 'multilingual'],
        category: 'text',
        isLatest: false,
        notes: 'Claude Sonnet 3.7 on AWS Bedrock - high-performance model with early extended thinking (deprecated)'
    },
    {
        modelId: 'anthropic.claude-3-5-sonnet-20241022-v1:0',
        modelName: 'Claude Sonnet 3.5 v2',
        provider: 'AWS Bedrock',
        inputPrice: 3.00,
        outputPrice: 15.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning', 'multilingual'],
        category: 'text',
        isLatest: false,
        notes: 'Claude Sonnet 3.5 v2 on AWS Bedrock - upgraded version'
    },
    {
        modelId: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
        modelName: 'Claude 3.5 Sonnet',
        provider: 'AWS Bedrock',
        inputPrice: 3.00,
        outputPrice: 15.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning'],
        category: 'text',
        isLatest: false,
        notes: 'Claude 3.5 Sonnet on AWS Bedrock - advanced reasoning and analysis capabilities'
    },
    {
        modelId: 'anthropic.claude-3-5-haiku-20241022-v1:0',
        modelName: 'Claude 3.5 Haiku',
        provider: 'AWS Bedrock',
        inputPrice: 0.80,
        outputPrice: 4.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'multilingual'],
        category: 'text',
        isLatest: false,
        notes: 'Claude 3.5 Haiku on AWS Bedrock - fast and intelligent for quick responses (superseded by Haiku 4.5)'
    },
    {
        modelId: 'anthropic.claude-3-opus-20240229-v1:0',
        modelName: 'Claude Opus 3',
        provider: 'AWS Bedrock',
        inputPrice: 15.00,
        outputPrice: 75.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multimodal', 'reasoning'],
        category: 'text',
        isLatest: false,
        notes: 'Claude Opus 3 on AWS Bedrock (legacy)'
    },
    {
        modelId: 'anthropic.claude-3-haiku-20240307-v1:0',
        modelName: 'Claude Haiku 3',
        provider: 'AWS Bedrock',
        inputPrice: 0.25,
        outputPrice: 1.25,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 200_000,
        capabilities: ['text', 'vision', 'multilingual'],
        category: 'text',
        isLatest: false,
        notes: 'Claude Haiku 3 on AWS Bedrock (legacy)'
    },

    // Cohere Models on AWS Bedrock
    {
        modelId: 'cohere.command-r-plus-v1:0',
        modelName: 'Command R+',
        provider: 'AWS Bedrock',
        inputPrice: 2.50,
        outputPrice: 10.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'multilingual', 'enterprise'],
        category: 'text',
        isLatest: true,
        notes: 'Cohere Command R+ - advanced AI model for text generation and chat'
    },
    {
        modelId: 'cohere.command-r-v1:0',
        modelName: 'Command R',
        provider: 'AWS Bedrock',
        inputPrice: 0.15,
        outputPrice: 0.60,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'multilingual', 'rag', 'tools'],
        category: 'text',
        isLatest: true,
        notes: 'Cohere Command R - advanced AI model for text generation and chat'
    },
    {
        modelId: 'cohere.embed-english-v3',
        modelName: 'Embed English v3',
        provider: 'AWS Bedrock',
        inputPrice: 0.10,
        outputPrice: 0.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 512,
        capabilities: ['embedding'],
        category: 'embedding',
        isLatest: true,
        notes: 'Cohere Embed English v3 - advanced AI model for text generation and chat'
    },
    {
        modelId: 'cohere.embed-multilingual-v3',
        modelName: 'Embed Multilingual v3',
        provider: 'AWS Bedrock',
        inputPrice: 0.10,
        outputPrice: 0.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 512,
        capabilities: ['embedding', 'multilingual'],
        category: 'embedding',
        isLatest: true,
        notes: 'Cohere Embed Multilingual v3 - advanced AI model for text generation and chat'
    },

    // Meta Models on AWS Bedrock
    {
        modelId: 'meta.llama3-70b-instruct-v1:0',
        modelName: 'Llama 3 70B',
        provider: 'AWS Bedrock',
        inputPrice: 0.10,
        outputPrice: 0.10,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 8192,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: true,
        notes: 'Meta Llama 3 70B - advanced AI model for text generation and chat'
    },
    {
        modelId: 'meta.llama3-8b-instruct-v1:0',
        modelName: 'Llama 3 8B',
        provider: 'AWS Bedrock',
        inputPrice: 0.05,
        outputPrice: 0.10,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 8192,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: true,
        notes: 'Meta Llama 3 8B - advanced AI model for text generation and chat'
    },
    {
        modelId: 'meta.llama3-2-11b-instruct-v1:0',
        modelName: 'Llama 3.2 11B',
        provider: 'AWS Bedrock',
        inputPrice: 0.16,
        outputPrice: 0.16,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'instruct', 'vision'],
        category: 'multimodal',
        isLatest: true,
        notes: 'Meta Llama 3.2 11B - advanced AI model for text generation and chat'
    },
    {
        modelId: 'meta.llama3-2-90b-instruct-v1:0',
        modelName: 'Llama 3.2 90B',
        provider: 'AWS Bedrock',
        inputPrice: 0.72,
        outputPrice: 0.72,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'instruct', 'vision'],
        category: 'multimodal',
        isLatest: true,
        notes: 'Meta Llama 3.2 90B - advanced AI model for text generation and chat'
    },
    {
        modelId: 'meta.llama4-scout-17b-instruct-v1:0',
        modelName: 'Llama 4 Scout',
        provider: 'AWS Bedrock',
        inputPrice: 0.17,
        outputPrice: 0.66,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'instruct', 'vision'],
        category: 'multimodal',
        isLatest: true,
        notes: 'Meta Llama 4 Scout 17B - advanced AI model for text generation and chat'
    },
    {
        modelId: 'meta.llama4-maverick-17b-instruct-v1:0',
        modelName: 'Llama 4 Maverick',
        provider: 'AWS Bedrock',
        inputPrice: 0.24,
        outputPrice: 0.97,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['text', 'instruct', 'vision'],
        category: 'multimodal',
        isLatest: true,
        notes: 'Meta Llama 4 Maverick 17B - advanced AI model for text generation and chat'
    },

    // Mistral AI Models on AWS Bedrock
    {
        modelId: 'mistral.mistral-7b-instruct-v0:2',
        modelName: 'Mistral 7B Instruct',
        provider: 'AWS Bedrock',
        inputPrice: 0.14,
        outputPrice: 0.42,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 32768,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: false,
        notes: 'Mistral 7B Instruct on AWS Bedrock'
    },
    {
        modelId: 'mistral.mixtral-8x7b-instruct-v0:1',
        modelName: 'Mixtral 8x7B Instruct',
        provider: 'AWS Bedrock',
        inputPrice: 0.14,
        outputPrice: 0.42,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 32768,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: false,
        notes: 'Mistral Mixtral 8x7B Instruct on AWS Bedrock'
    },
    {
        modelId: 'mistral.mistral-large-2402-v1:0',
        modelName: 'Mistral Large (24.02)',
        provider: 'AWS Bedrock',
        inputPrice: 6.50,
        outputPrice: 25.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 32768,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: true,
        notes: 'Mistral Large on AWS Bedrock'
    },
    {
        modelId: 'mistral.mistral-small-2402-v1:0',
        modelName: 'Mistral Small',
        provider: 'AWS Bedrock',
        inputPrice: 2.00,
        outputPrice: 6.00,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 32768,
        capabilities: ['text', 'instruct'],
        category: 'text',
        isLatest: true,
        notes: 'Mistral Small - advanced AI model for text generation and chat'
    },
    {
        modelId: 'mistral.pixtral-large-2502-v1:0',
        modelName: 'Pixtral Large',
        provider: 'AWS Bedrock',
        inputPrice: 2.0,
        outputPrice: 6.0,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 128000,
        capabilities: ['vision', 'multimodal', 'reasoning'],
        category: 'multimodal',
        isLatest: true,
        notes: 'Mistral Pixtral Large - advanced AI model for text generation and chat'
    },

    // DeepSeek Models
    {
        modelId: 'deepseek.r1-v1:0',
        modelName: 'DeepSeek R1',
        provider: 'AWS Bedrock',
        inputPrice: 1.35,
        outputPrice: 5.4,
        unit: PricingUnit.PER_1M_TOKENS,
        contextWindow: 64000,
        capabilities: ['text', 'reasoning', 'cot'],
        category: 'reasoning',
        isLatest: true,
        notes: 'DeepSeek R1 - advanced AI model for text generation and chat'
    },

    // Stability AI Models
    {
        modelId: 'stability.stable-diffusion-xl-v1:0',
        modelName: 'Stable Diffusion XL',
        provider: 'AWS Bedrock',
        inputPrice: 0.18,
        outputPrice: 0.18,
        unit: PricingUnit.PER_REQUEST,
        contextWindow: 0,
        capabilities: ['image-generation'],
        category: 'image',
        isLatest: true,
        notes: 'Stability AI Stable Diffusion XL - advanced AI model for text generation and chat'
    },

    // TwelveLabs Models
    {
        modelId: 'twelvelabs.pegasus-1-2-v1:0',
        modelName: 'Pegasus v1.2',
        provider: 'AWS Bedrock',
        inputPrice: 0.0,
        outputPrice: 0.0,
        unit: PricingUnit.PER_REQUEST,
        contextWindow: 0,
        capabilities: ['text', 'video', 'multimodal'],
        category: 'multimodal',
        isLatest: true,
        notes: 'TwelveLabs Pegasus v1.2 - advanced AI model for text generation and chat'
    },
    {
        modelId: 'twelvelabs.marengo-embed-2-7-v1:0',
        modelName: 'Marengo Embed v2.7',
        provider: 'AWS Bedrock',
        inputPrice: 0.0,
        outputPrice: 0.0,
        unit: PricingUnit.PER_REQUEST,
        contextWindow: 0,
        capabilities: ['embedding', 'multimodal'],
        category: 'embedding',
        isLatest: true,
        notes: 'TwelveLabs Marengo Embed v2.7 - advanced AI model for text generation and chat'
    }
]; 