import { ModelPricing, PricingUnit } from './types';

export const AWS_BEDROCK_PRICING: ModelPricing[] = [
  // Amazon Nova Models
  {
    modelId: 'amazon.nova-micro-v1:0',
    modelName: 'Nova Micro',
    provider: 'AWS Bedrock',
    inputPrice: 0.035,
    outputPrice: 0.14,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Amazon Nova Micro - cost-effective for simple tasks',
  },
  {
    modelId: 'amazon.nova-lite-v1:0',
    modelName: 'Nova Lite',
    provider: 'AWS Bedrock',
    inputPrice: 0.06,
    outputPrice: 0.24,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 300000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Amazon Nova Lite - balanced performance',
  },
  {
    modelId: 'amazon.nova-pro-v1:0',
    modelName: 'Nova Pro',
    provider: 'AWS Bedrock',
    inputPrice: 0.8,
    outputPrice: 3.2,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 300000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Amazon Nova Pro - advanced reasoning capabilities',
  },

  // Anthropic Claude Models
  {
    modelId: 'anthropic.claude-3-haiku-20240307-v1:0',
    modelName: 'Claude 3 Haiku',
    provider: 'AWS Bedrock',
    inputPrice: 0.25,
    outputPrice: 1.25,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text'],
    category: 'text',
    isLatest: false,
    isLegacy: true,
    notes: 'Claude 3 Haiku - Legacy model (AWS Bedrock lifecycle)',
  },
  {
    modelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
    modelName: 'Claude 3 Sonnet',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: false,
    isLegacy: true,
    notes: 'Claude 3 Sonnet - Legacy model (AWS Bedrock lifecycle)',
  },
  {
    modelId: 'anthropic.claude-3-opus-20240229-v1:0',
    modelName: 'Claude 3 Opus',
    provider: 'AWS Bedrock',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'complex'],
    category: 'text',
    isLatest: false,
    isLegacy: true,
    notes: 'Claude 3 Opus - Legacy model (AWS Bedrock lifecycle)',
  },
  {
    modelId: 'anthropic.claude-3-5-sonnet-20240620-v1:0',
    modelName: 'Claude 3.5 Sonnet',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: false,
    isLegacy: true,
    notes: 'Claude 3.5 Sonnet - Legacy model (marked by AWS Bedrock)',
  },
  {
    modelId: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    modelName: 'Claude 3.5 Sonnet v2',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3.5 Sonnet v2 - improved reasoning',
  },
  {
    modelId: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    modelName: 'Claude 3.5 Haiku',
    provider: 'AWS Bedrock',
    inputPrice: 0.8,
    outputPrice: 4.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'analysis'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3.5 Haiku v2 - fast and cost-effective',
  },
  {
    // Haiku 4.5 is only served on Bedrock via a global cross-region inference
    // profile, hence the `global.` prefix. The `convertToInferenceProfile`
    // helper prepends a regional prefix (e.g. `us.global.anthropic...`) before
    // sending to Bedrock, so we register both forms for pricing lookups.
    modelId: 'global.anthropic.claude-haiku-4-5-20251001-v1:0',
    modelName: 'Claude Haiku 4.5',
    provider: 'AWS Bedrock',
    inputPrice: 1.0,
    outputPrice: 5.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'analysis'],
    category: 'text',
    isLatest: true,
    notes:
      'Claude Haiku 4.5 - 1/3 the price of Sonnet 4.5, near-Sonnet quality',
  },
  {
    modelId: 'us.global.anthropic.claude-haiku-4-5-20251001-v1:0',
    modelName: 'Claude Haiku 4.5 (US)',
    provider: 'AWS Bedrock',
    inputPrice: 1.0,
    outputPrice: 5.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'analysis'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Haiku 4.5 US global inference profile',
  },

  // Claude 4 and 4.5 models (2025)
  {
    modelId: 'anthropic.claude-sonnet-4-20250514-v1:0',
    modelName: 'Claude Sonnet 4',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4 - balanced performance',
  },
  {
    modelId: 'anthropic.claude-sonnet-4-5-20250929-v1:0',
    modelName: 'Claude Sonnet 4.5',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding', 'agents'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4.5 - best for coding and complex agents',
  },
  {
    modelId: 'anthropic.claude-opus-4-6-v1',
    modelName: 'Claude Opus 4.6',
    provider: 'AWS Bedrock',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding', 'agents'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4.6 - most intelligent for agents',
  },
  {
    modelId: 'anthropic.claude-sonnet-4-6',
    modelName: 'Claude Sonnet 4.6',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Sonnet 4.6 - best balance of speed and intelligence',
  },
  // US region inference profile IDs (cross-region)
  {
    modelId: 'us.anthropic.claude-opus-4-1-20250805-v1:0',
    modelName: 'Claude Opus 4.1 (US)',
    provider: 'AWS Bedrock',
    inputPrice: 15.0,
    outputPrice: 75.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'Claude Opus 4.1 inference profile',
  },
  {
    modelId: 'us.anthropic.claude-3-5-sonnet-20241022-v2:0',
    modelName: 'Claude 3.5 Sonnet v2 (US)',
    provider: 'AWS Bedrock',
    inputPrice: 3.0,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3.5 Sonnet v2 inference profile',
  },
  {
    modelId: 'us.anthropic.claude-3-5-haiku-20241022-v1:0',
    modelName: 'Claude 3.5 Haiku v2 (US)',
    provider: 'AWS Bedrock',
    inputPrice: 0.25,
    outputPrice: 1.25,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Claude 3.5 Haiku v2 inference profile',
  },
  {
    modelId: 'us.amazon.nova-pro-v1:0',
    modelName: 'Nova Pro (US)',
    provider: 'AWS Bedrock',
    inputPrice: 0.8,
    outputPrice: 3.2,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 300000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Nova Pro inference profile',
  },
  {
    modelId: 'us.amazon.nova-lite-v1:0',
    modelName: 'Nova Lite (US)',
    provider: 'AWS Bedrock',
    inputPrice: 0.06,
    outputPrice: 0.24,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 300000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Nova Lite inference profile',
  },

  // Meta Llama Models
  {
    modelId: 'meta.llama3-1-8b-instruct-v1:0',
    modelName: 'Llama 3.1 8B',
    provider: 'AWS Bedrock',
    inputPrice: 0.22,
    outputPrice: 0.22,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Meta Llama 3.1 8B - efficient open source model',
  },
  {
    modelId: 'meta.llama3-1-70b-instruct-v1:0',
    modelName: 'Llama 3.1 70B',
    provider: 'AWS Bedrock',
    inputPrice: 2.65,
    outputPrice: 3.5,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'Meta Llama 3.1 70B - powerful reasoning model',
  },

  // Mistral AI Models
  {
    modelId: 'mistral.mistral-large-3-675b-instruct',
    modelName: 'Mistral Large 3',
    provider: 'AWS Bedrock',
    inputPrice: 0.5,
    outputPrice: 1.5,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 256000,
    capabilities: ['text', 'reasoning', 'coding'],
    category: 'text',
    isLatest: true,
    notes: 'Mistral Large 3 - $0.50/$1.50 per 1M, 256K context, 8K output',
  },
];
