import { ModelPricing, PricingUnit } from './types';

export const GOOGLE_PRICING: ModelPricing[] = [
  // Gemini 3 family (developer API — verify model id strings on ai.google.dev)
  {
    modelId: 'gemini-3-pro-preview',
    modelName: 'Gemini 3 Pro (preview)',
    provider: 'Google',
    inputPrice: 2.0,
    outputPrice: 12.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 2_000_000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Gemini 3-class Pro preview — pricing indicative; confirm on Google AI pricing',
  },
  {
    modelId: 'gemini-3-flash-preview',
    modelName: 'Gemini 3 Flash (preview)',
    provider: 'Google',
    inputPrice: 0.35,
    outputPrice: 2.8,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Gemini 3-class Flash preview — verify live id',
  },
  {
    modelId: 'gemini-3.1-pro',
    modelName: 'Gemini 3.1 Pro',
    provider: 'Google',
    inputPrice: 2.0,
    outputPrice: 12.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 2_000_000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Gemini 3.1 Pro — align id with Vertex/Gemini API release notes',
  },
  // Gemini 2.5
  {
    modelId: 'gemini-2.5-pro',
    modelName: 'Gemini 2.5 Pro',
    provider: 'Google',
    inputPrice: 1.25,
    outputPrice: 10.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 2_000_000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Gemini 2.5 Pro',
  },
  {
    modelId: 'gemini-2.5-flash',
    modelName: 'Gemini 2.5 Flash',
    provider: 'Google',
    inputPrice: 0.3,
    outputPrice: 2.5,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Gemini 2.5 Flash',
  },
  {
    modelId: 'gemini-2.5-flash-lite',
    modelName: 'Gemini 2.5 Flash-Lite',
    provider: 'Google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'High-throughput / cost-optimized 2.5',
  },
  {
    modelId: 'gemini-2.5-flash-lite-preview',
    modelName: 'Gemini 2.5 Flash-Lite (preview)',
    provider: 'Google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision', 'long-context'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Preview id variant',
  },
  // Gemini 2.0
  {
    modelId: 'gemini-2.0-flash',
    modelName: 'Gemini 2.0 Flash',
    provider: 'Google',
    inputPrice: 0.1,
    outputPrice: 0.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision', 'long-context'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Gemini 2.0 Flash',
  },
  {
    modelId: 'gemini-2.0-flash-lite',
    modelName: 'Gemini 2.0 Flash-Lite',
    provider: 'Google',
    inputPrice: 0.075,
    outputPrice: 0.3,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_000_000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Gemini 2.0 Flash-Lite',
  },
  // Gemini 1.5
  {
    modelId: 'gemini-1.5-flash',
    modelName: 'Gemini 1.5 Flash',
    provider: 'Google',
    inputPrice: 0.075,
    outputPrice: 0.3,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1000000,
    capabilities: ['text', 'vision', 'long-context'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Gemini 1.5 Flash - fast multimodal model with 1M context',
  },
  {
    modelId: 'gemini-1.5-pro',
    modelName: 'Gemini 1.5 Pro',
    provider: 'Google',
    inputPrice: 1.25,
    outputPrice: 5.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1000000,
    capabilities: ['text', 'vision', 'reasoning', 'long-context'],
    category: 'multimodal',
    isLatest: false,
    notes: 'Gemini 1.5 Pro - advanced multimodal reasoning with 1M context',
  },
];
