import { ModelPricing, PricingUnit } from './types';

/**
 * OpenAI public API pricing (USD per 1M tokens unless noted).
 * Verified from platform docs / announcements — re-check periodically on openai.com/pricing.
 */
export const OPENAI_PRICING: ModelPricing[] = [
  // GPT-5.5 family (frontier)
  {
    modelId: 'gpt-5.5',
    modelName: 'GPT-5.5',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-5.5 — flagship; pricing per OpenAI API docs',
  },
  {
    modelId: 'gpt-5.5-2026-04-23',
    modelName: 'GPT-5.5 (2026-04-23 snapshot)',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Dated snapshot of GPT-5.5',
  },
  {
    modelId: 'gpt-5.5-pro',
    modelName: 'GPT-5.5 Pro',
    provider: 'OpenAI',
    inputPrice: 30.0,
    outputPrice: 180.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Higher-quality GPT-5.5 tier',
  },
  // GPT-5.4
  {
    modelId: 'gpt-5.4',
    modelName: 'GPT-5.4',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 15.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 256_000,
    capabilities: ['text', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-5.4',
  },
  {
    modelId: 'gpt-5.4-mini',
    modelName: 'GPT-5.4 Mini',
    provider: 'OpenAI',
    inputPrice: 0.75,
    outputPrice: 4.5,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 256_000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Faster, lower-cost GPT-5.4',
  },
  // GPT-5 aliases (API model strings)
  {
    modelId: 'gpt-5',
    modelName: 'GPT-5',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning', 'tools'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Alias / family id — align with live API id you call',
  },
  {
    modelId: 'gpt-5-mini',
    modelName: 'GPT-5 Mini',
    provider: 'OpenAI',
    inputPrice: 0.75,
    outputPrice: 4.5,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 256_000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Efficient GPT-5-class model',
  },
  {
    modelId: 'gpt-5-nano',
    modelName: 'GPT-5 Nano',
    provider: 'OpenAI',
    inputPrice: 0.2,
    outputPrice: 0.8,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'Smallest GPT-5-class latency/cost tier (estimate — verify on pricing page)',
  },
  {
    modelId: 'gpt-5-chat',
    modelName: 'GPT-5 Chat',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Chat-optimized GPT-5 variant',
  },
  {
    modelId: 'gpt-5-chat-latest',
    modelName: 'GPT-5 Chat (latest)',
    provider: 'OpenAI',
    inputPrice: 5.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_050_000,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'Rolling chat alias',
  },
  // Reasoning models (o-series)
  {
    modelId: 'o1',
    modelName: 'o1',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Reasoning model — includes reasoning tokens in output pricing',
  },
  {
    modelId: 'o1-mini',
    modelName: 'o1-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: false,
    notes: 'Smaller reasoning model',
  },
  {
    modelId: 'o1-2024-12-17',
    modelName: 'o1 (2024-12-17)',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: false,
    notes: 'o1 snapshot',
  },
  {
    modelId: 'o3',
    modelName: 'o3',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: true,
    notes: 'o3 reasoning',
  },
  {
    modelId: 'o3-mini',
    modelName: 'o3-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: true,
    notes: 'o3-mini',
  },
  {
    modelId: 'o3-2025-04-16',
    modelName: 'o3 (2025-04-16)',
    provider: 'OpenAI',
    inputPrice: 15.0,
    outputPrice: 60.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: true,
    notes: 'o3 dated snapshot',
  },
  {
    modelId: 'o3-mini-2025-01-31',
    modelName: 'o3-mini (2025-01-31)',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: true,
    notes: 'o3-mini snapshot',
  },
  {
    modelId: 'o4-mini',
    modelName: 'o4-mini',
    provider: 'OpenAI',
    inputPrice: 1.1,
    outputPrice: 4.4,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 200_000,
    capabilities: ['reasoning'],
    category: 'reasoning',
    isLatest: true,
    notes: 'o4-mini (estimate — verify)',
  },
  // GPT-4.1 / GPT-4o generation
  {
    modelId: 'gpt-4.1',
    modelName: 'GPT-4.1',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_047_576,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-4.1',
  },
  {
    modelId: 'gpt-4.1-2025-04-14',
    modelName: 'GPT-4.1 (2025-04-14)',
    provider: 'OpenAI',
    inputPrice: 2.0,
    outputPrice: 8.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 1_047_576,
    capabilities: ['text', 'vision', 'reasoning'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-4.1 snapshot',
  },
  {
    modelId: 'gpt-4o-2024-08-06',
    modelName: 'GPT-4o (2024-08-06)',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: false,
    notes: 'GPT-4o snapshot',
  },
  {
    modelId: 'gpt-4o-mini-2024-07-18',
    modelName: 'GPT-4o mini (2024-07-18)',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: false,
    notes: 'GPT-4o mini snapshot',
  },
  {
    modelId: 'gpt-4o-mini',
    modelName: 'GPT-4o Mini',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-4o Mini - cost-effective and fast',
  },
  {
    modelId: 'gpt-4o',
    modelName: 'GPT-4o',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-4o - advanced multimodal model',
  },
  {
    modelId: 'gpt-4-turbo',
    modelName: 'GPT-4 Turbo',
    provider: 'OpenAI',
    inputPrice: 10.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128_000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: false,
    notes: 'GPT-4 Turbo - legacy high-capability',
  },
];
