import { ModelPricing, PricingUnit } from './types';

export const OPENAI_PRICING: ModelPricing[] = [
  {
    modelId: 'gpt-4o-mini',
    modelName: 'GPT-4o Mini',
    provider: 'OpenAI',
    inputPrice: 0.15,
    outputPrice: 0.6,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text'],
    category: 'text',
    isLatest: true,
    notes: 'GPT-4o Mini - cost-effective and fast',
  },
  {
    modelId: 'gpt-4o',
    modelName: 'GPT-4o',
    provider: 'OpenAI',
    inputPrice: 2.5,
    outputPrice: 10.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text', 'vision'],
    category: 'multimodal',
    isLatest: true,
    notes: 'GPT-4o - advanced multimodal model',
  },
  {
    modelId: 'gpt-4-turbo',
    modelName: 'GPT-4 Turbo',
    provider: 'OpenAI',
    inputPrice: 10.0,
    outputPrice: 30.0,
    unit: PricingUnit.PER_1M_TOKENS,
    contextWindow: 128000,
    capabilities: ['text', 'reasoning'],
    category: 'text',
    isLatest: true,
    notes: 'GPT-4 Turbo - powerful reasoning model',
  },
];
