import { Router } from 'express';
import metricsRouter from './metrics.route';
import authRouter from './auth.routes';
import userRouter from './user.routes';
import usageRouter from './usage.routes';
import optimizationRouter from './optimization.routes';
import analyticsRouter from './analytics.routes';
import { trackerRouter } from './tracker.routes';
import intelligenceRoutes from './intelligence.routes';
import projectRoutes from './project.routes';
import promptTemplateRoutes from './promptTemplate.routes';
import { pricingRoutes } from './pricing.routes';
import taggingRoutes from './tagging.routes';
import performanceCostAnalysisRoutes from './performanceCostAnalysis.routes';
import experimentationRoutes from './experimentation.routes';
import chatRoutes from './chat.routes';
import agentRoutes from './agent.routes';
import { chatgptRoutes } from './chatgpt.routes';
import { cursorRoutes } from './cursor.routes';
import { apiKeyRoutes } from './apiKey.routes';
import { onboardingRoutes } from './onboarding.routes';
import { onboardingApiRoutes } from './onboarding-api.routes';
import { monitoringRoutes } from './monitoring.routes';
import { gatewayRoutes } from './gateway.routes';
import workflowRoutes from './workflow.routes';
import memoryRoutes from './memory.routes';
import keyVaultRoutes from './keyVault.routes';
import requestFeedbackRoutes from './requestFeedback.routes';
import simulationTrackingRoutes from './simulationTracking.routes';
import autoSimulationRoutes from './autoSimulation.routes';
import predictiveIntelligenceRoutes from './predictiveIntelligence.routes';
import cacheRoutes from './cache.routes';
import budgetRoutes from './budget.routes';
import trackingRoutes from './tracking.routes';
import traceRoutes from './trace.routes';
import telemetryRoutes from './telemetry.routes';
import ckqlRoutes from './ckql.routes';
import notebookRoutes from './notebook.routes';
import guardrailsRoutes from './guardrails.routes';
import webhookRoutes from './webhook.routes';
import mfaRoutes from './mfa.routes';
import moderationRoutes from './moderation.routes';
import { securityRoutes } from './security.routes';
import unexplainedCostRoutes from './unexplainedCost.routes';
import cortexTrainingDataRoutes from './cortexTrainingData.routes';
import backupRoutes from './backupRoutes';
import emailTrackingRoutes from './emailTracking.routes';
import aiCostMonitoringRoutes from './admin/aiCostMonitoring.routes';
import userSpendingRoutes from './admin/userSpending.routes';
import dashboardRoutes from './admin/dashboard.routes';
import discountRoutes from './admin/discounts.routes';
import ingestionRoutes from './ingestion.routes';
import userTelemetryConfigRoutes from './userTelemetryConfig.routes';
import sessionReplayRoutes from './sessionReplay.routes';
import backupCodesRoutes from './backupCodes.routes';
import teamRoutes from './team.routes';
import integrationRoutes from './integration.routes';
import githubRoutes from './github.routes';
import githubWebhookRoutes from './githubWebhooks.routes';
import visualComplianceRoutes from './visualCompliance.routes';
import logsRoutes from './logs.routes';
import referenceImageRoutes from './referenceImage.routes';
import templateAnalyticsRoutes from './templateAnalytics.routes';
import docsAnalyticsRoutes from './docsAnalytics.routes';
import communityRoutes from './community.routes';
import automationRoutes from './automation.routes';
import billingRoutes from './billing.routes';
import paymentWebhookRoutes from './paymentWebhook.routes';
import brainRoutes from './brain.routes';
import costStreamingRoutes from './costStreaming.routes';
import costIntelligenceRoutes from './costIntelligence.routes';
import costIntelligenceConfigRoutes from './costIntelligenceConfig.routes';
import agentGovernanceRoutes from './agentGovernance.routes';
import dataNetworkEffectsRoutes from './dataNetworkEffects.routes';
import proactiveSuggestionsRoutes from './proactiveSuggestions.routes';

const router = Router();

// Health check
router.get('/health', (_, res) => {
    res.status(200).json({ status: 'Cost Katana Backend API' });
});

// API version
router.get('/version', (_, res) => {
    res.status(200).json({ version: process.env.npm_package_version });
});

// Mount routes
router.use('/auth', authRouter);
router.use('/user', userRouter);
router.use('/usage', usageRouter);
router.use('/optimizations', optimizationRouter);
router.use('/analytics', analyticsRouter);
router.use('/tracker', trackerRouter);
router.use('/intelligence', intelligenceRoutes);
router.use('/projects', projectRoutes);
router.use('/prompt-templates', promptTemplateRoutes);
router.use('/templates/analytics', templateAnalyticsRoutes);
router.use('/pricing', pricingRoutes);
router.use('/tags', taggingRoutes);
router.use('/performance-cost', performanceCostAnalysisRoutes);
router.use('/experimentation', experimentationRoutes);
router.use('/chat', chatRoutes);
router.use('/agent', agentRoutes);
router.use('/chatgpt', chatgptRoutes);
router.use('/cursor', cursorRoutes);
router.use('/api-keys', apiKeyRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/onboarding', onboardingApiRoutes);
router.use('/monitoring', monitoringRoutes);
router.use('/gateway', gatewayRoutes);
router.use('/metrics', metricsRouter);
router.use('/workflows', workflowRoutes);
router.use('/memory', memoryRoutes);
router.use('/key-vault', keyVaultRoutes);
router.use('/v1', requestFeedbackRoutes);
router.use('/simulation-tracking', simulationTrackingRoutes);
router.use('/auto-simulation', autoSimulationRoutes);
router.use('/predictive-intelligence', predictiveIntelligenceRoutes);
router.use('/cache', cacheRoutes);
router.use('/budget', budgetRoutes);
router.use('/tracking', trackingRoutes);
router.use('/v1', traceRoutes);
router.use('/telemetry', telemetryRoutes);
router.use('/ckql', ckqlRoutes);
router.use('/notebooks', notebookRoutes);
router.use('/guardrails', guardrailsRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/mfa', mfaRoutes);
router.use('/moderation', moderationRoutes);
router.use('/security', securityRoutes);
router.use('/unexplained-costs', unexplainedCostRoutes);
router.use('/cortex-training-data', cortexTrainingDataRoutes);
router.use('/backup', backupRoutes);
router.use('/email', emailTrackingRoutes);
router.use('/admin/ai-costs', aiCostMonitoringRoutes);
router.use('/admin/users/spending', userSpendingRoutes);
router.use('/admin/discounts', discountRoutes);
router.use('/admin', dashboardRoutes);
router.use('/ingestion', ingestionRoutes);
router.use('/telemetry-config', userTelemetryConfigRoutes);
router.use('/session-replay', sessionReplayRoutes);
router.use('/backup-codes', backupCodesRoutes);
router.use('/team', teamRoutes);
router.use('/integrations', integrationRoutes);
router.use('/github', githubRoutes);
router.use('/github', githubWebhookRoutes);
router.use('/visual-compliance', visualComplianceRoutes);
router.use('/logs', logsRoutes);
router.use('/templates', referenceImageRoutes);
router.use('/reference-image', referenceImageRoutes);
router.use('/docs-analytics', docsAnalyticsRoutes);
router.use('/community', communityRoutes);
router.use('/automation', automationRoutes);
router.use('/billing', billingRoutes);
router.use('/webhooks/payment', paymentWebhookRoutes);
router.use('/brain', brainRoutes);
router.use('/cost-streaming', costStreamingRoutes);
router.use('/cost-intelligence', costIntelligenceRoutes);
router.use('/cost-intelligence-config', costIntelligenceConfigRoutes);
router.use('/agent-governance', agentGovernanceRoutes);
router.use('/data-network-effects', dataNetworkEffectsRoutes);
router.use('/proactive-suggestions', proactiveSuggestionsRoutes);

export const apiRouter = router;
