/**
 * Cortex Decoder Service
 *
 * Decodes Cortex semantic frames back into natural language text.
 * Handles the final stage of the Cortex processing pipeline.
 */

import { Injectable, Logger } from '@nestjs/common';
import {
  CortexDecodingRequest,
  CortexDecodingResult,
  CortexFrame,
} from '../types/cortex.types';
import { AIRouterService } from './ai-router.service';
import { CortexCacheService } from './cortex-cache.service';
import { DEFAULT_CORTEX_CONFIG } from '../types/cortex.types';

// Cortex Decoder System Prompt - Source of Truth from Express Backend
const CORTEX_DECODER_SYSTEM_PROMPT = `You are a Cortex Decoder - a specialized AI that converts LISP-encoded ANSWERS into natural, fluent language.

🚨 NEW ARCHITECTURE: You are decoding ANSWERS generated by the Core Processor, not optimized prompts.

🚨 SPECIAL HANDLING FOR CODE ANSWERS:
When you see a code response (either as "answer: code_[...]" or a JSON object with code field), you MUST:
1. Extract the COMPLETE code from the code_ field or code property
2. Format it properly with correct indentation
3. Include ALL the code - every function, every line
4. Present it as a complete, runnable program
5. Add brief explanatory comments if needed for clarity

CORTEX DECODING RULES:
1. Convert Cortex structures into natural, grammatically correct language
2. Preserve ALL semantic meaning from the original Cortex structure - ZERO INFORMATION LOSS
3. For answers containing code, present the code clearly with proper formatting
4. Use natural, conversational language that directly addresses the user's query
5. Include ALL entities, concepts, numbers, dates, and technical details
6. When decoding answer frames, present the information as a direct response to the original question

🎯 ANSWER FRAME DECODING (PRIMARY FOCUS):
- value_X → "The answer is X" or just "X" for simple values
- content_X → Expand X into natural language
- list_[a,b,c] → Present as a formatted list
- code_[actual_code_here] → Format as complete, runnable code with proper syntax
- entity_[name] → Describe the entity clearly
- action_[what_to_do] → Explain the action in natural language

OUTPUT ONLY NATURAL LANGUAGE - NO CORTEX SYNTAX IN THE RESPONSE.`;

@Injectable()
export class CortexDecoderService {
  private readonly logger = new Logger(CortexDecoderService.name);

  constructor(
    private readonly aiRouter: AIRouterService,
    private readonly cache: CortexCacheService,
  ) {}

  /**
   * Decode a Cortex frame into natural language text
   */
  async decode(request: CortexDecodingRequest): Promise<CortexDecodingResult> {
    const startTime = Date.now();

    try {
      // Check cache first
      const cacheKey = `decode_${this.generateCacheKey(request)}`;
      const cached = this.cache.get(cacheKey);
      if (cached) {
        this.logger.debug('Decoding result found in cache');
        return cached as unknown as CortexDecodingResult;
      }

      // Generate decoding prompt
      const prompt = this.buildDecodingPrompt(request);

      // Invoke AI model
      const aiResult = await this.aiRouter.invokeModel({
        model:
          request.config?.decoding?.model ??
          DEFAULT_CORTEX_CONFIG.decoding.model,
        prompt,
        parameters: {
          temperature: this.getDecodingTemperature(request),
          maxTokens: 4000,
        },
        metadata: {
          requestId: `decode_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        },
      });

      // Parse and clean the response
      const decodedText = this.parseDecodingResponse(aiResult.response);

      // Apply post-processing
      const processedText = this.postProcessDecodedText(decodedText, request);

      // Calculate fidelity score
      const fidelityScore = await this.calculateFidelityScore(
        request.cortexStructure,
        decodedText,
      );

      // Analyze quality metrics
      const qualityMetrics = await this.analyzeQualityMetrics(
        decodedText,
        request,
      );

      const result: CortexDecodingResult = {
        text: processedText,
        confidence:
          aiResult.usage.totalTokens > 0
            ? Math.min(1, aiResult.usage.totalTokens / 1000)
            : 0.8,
        processingTime: Date.now() - startTime,
        fidelityScore,
        metadata: {
          decodingModel: aiResult.model,
          targetLanguage: request.targetLanguage || 'en',
          styleApplied: request.style || 'conversational',
          qualityMetrics,
          postProcessingApplied: this.getPostProcessingSteps(request),
        },
      };

      // Cache the result
      this.cache.set(cacheKey, result as any, {
        ttl: 7200000, // 2 hours
        type: 'decoding',
        tags: [
          'decoding',
          request.targetLanguage || 'en',
          request.style || 'conversational',
        ],
        semanticHash: this.generateSemanticHash(request.cortexStructure),
      });

      this.logger.log(
        `Decoded Cortex frame to text in ${result.processingTime}ms with fidelity ${fidelityScore?.toFixed(2) || 'N/A'}`,
      );
      return result;
    } catch (error) {
      this.logger.error('Decoding failed', error);
      throw new Error(`Cortex decoding failed: ${error.message}`);
    }
  }

  /**
   * Batch decode multiple Cortex frames
   */
  async decodeBatch(
    requests: CortexDecodingRequest[],
  ): Promise<CortexDecodingResult[]> {
    const promises = requests.map((request) => this.decode(request));
    return await Promise.all(promises);
  }

  /**
   * Decode with specific style optimization
   */
  async decodeWithStyle(
    cortexStructure: CortexFrame,
    style:
      | 'formal'
      | 'casual'
      | 'technical'
      | 'conversational' = 'conversational',
    options?: Partial<CortexDecodingRequest>,
  ): Promise<CortexDecodingResult> {
    return this.decode({
      cortexStructure,
      style,
      ...options,
    });
  }

  /**
   * Decode for specific audience level
   */
  async decodeForAudience(
    cortexStructure: CortexFrame,
    audienceLevel: 'beginner' | 'intermediate' | 'expert',
    options?: Partial<CortexDecodingRequest>,
  ): Promise<CortexDecodingResult> {
    const styleMap = {
      beginner: 'casual',
      intermediate: 'conversational',
      expert: 'technical',
    };

    return this.decode({
      cortexStructure,
      style: styleMap[audienceLevel] as
        | 'formal'
        | 'casual'
        | 'technical'
        | 'conversational',
      options: {
        enhanceReadability: audienceLevel === 'beginner',
        ...options?.options,
      },
      metadata: {
        audienceLevel,
        ...options?.metadata,
      },
      ...options,
    });
  }

  // Private methods

  private buildDecodingPrompt(request: CortexDecodingRequest): string {
    const frameInfo = this.analyzeFrameStructure(request.cortexStructure);
    const styleGuide = this.getStyleGuide(request.style || 'conversational');
    const languageInstruction =
      request.targetLanguage && request.targetLanguage !== 'en'
        ? `\nTranslate to ${request.targetLanguage}.`
        : '';

    const audienceInstruction = request.metadata?.audienceLevel
      ? `\nWrite for ${request.metadata.audienceLevel} audience level.`
      : '';

    const formattingInstruction =
      request.format !== 'plain' ? `\nFormat as ${request.format}.` : '';

    // Use answer-specific prompt when decoding answer frames
    if (request.options?.isAnswer) {
      return `${CORTEX_DECODER_SYSTEM_PROMPT}

CORTEX FRAME:
${JSON.stringify(request.cortexStructure, null, 2)}

FRAME ANALYSIS:
- Type: ${frameInfo.type}
- Complexity: ${frameInfo.complexity}
- Key elements: ${frameInfo.keyElements.join(', ')}

STYLE GUIDE:
${styleGuide}${languageInstruction}${audienceInstruction}${formattingInstruction}

OUTPUT ONLY NATURAL LANGUAGE - NO CORTEX SYNTAX IN THE RESPONSE.`;
    }

    return `
You are a Cortex Decoder. Your task is to convert a Cortex semantic frame into natural language text.

CORTEX FRAME:
${JSON.stringify(request.cortexStructure, null, 2)}

FRAME ANALYSIS:
- Type: ${frameInfo.type}
- Complexity: ${frameInfo.complexity}
- Key elements: ${frameInfo.keyElements.join(', ')}

STYLE GUIDE:
${styleGuide}

INSTRUCTIONS:
- Convert the semantic frame to fluent, natural language text
- Preserve all important information from the frame
- Use the specified style and tone
- Ensure the output is coherent and well-structured${languageInstruction}${audienceInstruction}${formattingInstruction}
- ${request.options?.enhanceReadability ? 'Enhance readability with clear explanations' : 'Be concise but complete'}

OUTPUT:
Provide only the decoded natural language text, no additional formatting or metadata.
`;
  }

  private analyzeFrameStructure(frame: CortexFrame): {
    type: string;
    complexity: string;
    keyElements: string[];
  } {
    const keyElements: string[] = [];

    // Extract key elements based on frame type
    switch (frame.frameType) {
      case 'query':
        keyElements.push(`Query: ${frame.action || 'unknown action'}`);
        if (frame.target) keyElements.push(`Target: ${frame.target}`);
        if (frame.aspect) keyElements.push(`Aspect: ${frame.aspect}`);
        break;

      case 'answer':
        keyElements.push(`Answer for: ${frame.for_task || 'unknown task'}`);
        keyElements.push(`Status: ${frame.status || 'complete'}`);
        if (frame.summary) keyElements.push(`Summary: ${frame.summary}`);
        break;

      case 'event':
        keyElements.push(`Action: ${frame.action || 'unknown'}`);
        if (frame.agent) keyElements.push(`Agent: ${frame.agent}`);
        if (frame.object) keyElements.push(`Object: ${frame.object}`);
        break;

      case 'entity':
        keyElements.push(`Entity: ${frame.name || frame.title || 'unnamed'}`);
        keyElements.push(`Type: ${frame.type || 'unknown'}`);
        break;

      default:
        keyElements.push(`Type: ${frame.frameType}`);
    }

    const complexity = Object.keys(frame).length > 5 ? 'complex' : 'simple';

    return {
      type: frame.frameType,
      complexity,
      keyElements,
    };
  }

  private getStyleGuide(style: string): string {
    const styleGuides = {
      formal: `- Use formal, professional language
- Avoid contractions (use "do not" instead of "don't")
- Use complete sentences
- Maintain objective, impersonal tone`,

      casual: `- Use conversational, friendly language
- Include contractions (it's, don't, etc.)
- Be approachable and relatable
- Use simple, everyday words`,

      technical: `- Use precise, technical terminology
- Include relevant technical details
- Maintain accuracy and specificity
- Use industry-standard jargon appropriately`,

      conversational: `- Use natural, spoken language style
- Include transitions and connecting phrases
- Be engaging and personable
- Vary sentence structure`,
    };

    return (
      styleGuides[style as keyof typeof styleGuides] ||
      styleGuides.conversational
    );
  }

  private getDecodingTemperature(request: CortexDecodingRequest): number {
    // Adjust temperature based on style and requirements
    const baseTemp = 0.3; // Lower temperature for more consistent decoding

    if (
      (request.style as string) === 'creative' ||
      request.style === 'casual'
    ) {
      return Math.min(0.7, baseTemp + 0.2);
    }

    if (request.options?.enhanceReadability) {
      return Math.max(0.1, baseTemp - 0.1);
    }

    return baseTemp;
  }

  private parseDecodingResponse(response: string): string {
    // Clean up the response - remove any extra formatting or metadata
    let cleaned = response.trim();

    // Remove common AI prefixes/suffixes
    cleaned = cleaned.replace(/^Here is the decoded text:\s*/i, '');
    cleaned = cleaned.replace(/^Decoded text:\s*/i, '');
    cleaned = cleaned.replace(/^Output:\s*/i, '');
    cleaned = cleaned.replace(/^Response:\s*/i, '');

    // Remove markdown code blocks if present
    cleaned = cleaned.replace(/^```[\s\S]*?```$/m, (match) => {
      return match.replace(/^```\w*\n?/, '').replace(/\n?```$/, '');
    });

    // Remove quotes if the entire response is quoted
    if (
      cleaned.startsWith('"') &&
      cleaned.endsWith('"') &&
      cleaned.length > 2
    ) {
      cleaned = cleaned.slice(1, -1);
    }

    return cleaned.trim();
  }

  private async calculateFidelityScore(
    originalFrame: CortexFrame,
    decodedText: string,
  ): Promise<number> {
    try {
      // Multi-dimensional fidelity assessment
      const lexicalFidelity = await this.calculateLexicalFidelity(
        originalFrame,
        decodedText,
      );
      const semanticFidelity = await this.calculateSemanticFidelity(
        originalFrame,
        decodedText,
      );
      const structuralFidelity = this.calculateStructuralFidelity(
        originalFrame,
        decodedText,
      );
      const contextualFidelity = await this.calculateContextualFidelity(
        originalFrame,
        decodedText,
      );

      // Weighted combination of fidelity metrics
      const overallFidelity =
        lexicalFidelity * 0.3 +
        semanticFidelity * 0.4 +
        structuralFidelity * 0.2 +
        contextualFidelity * 0.1;

      // Apply quality adjustment
      const qualityAdjustment = this.assessTextQuality(decodedText);

      // Length appropriateness factor
      const lengthFactor = this.calculateLengthAppropriateness(
        originalFrame,
        decodedText,
      );

      // Final score with quality and length adjustments
      const finalScore = Math.min(
        1.0,
        overallFidelity * qualityAdjustment * lengthFactor,
      );

      this.logger.debug(
        `Fidelity scores: lexical=${lexicalFidelity.toFixed(3)}, semantic=${semanticFidelity.toFixed(3)}, structural=${structuralFidelity.toFixed(3)}, contextual=${contextualFidelity.toFixed(3)}, final=${finalScore.toFixed(3)}`,
      );

      return finalScore;
    } catch (error) {
      this.logger.warn('Failed to calculate fidelity score', error);
      return 0.5; // Default moderate fidelity
    }
  }

  private async analyzeQualityMetrics(
    text: string,
    request: CortexDecodingRequest,
  ): Promise<CortexDecodingResult['metadata']['qualityMetrics']> {
    // Analyze fluency, coherence, and accuracy
    const fluency = this.assessFluency(text);
    const coherence = this.assessCoherence(text);
    const accuracy = await this.assessAccuracy(text, request);

    return {
      fluency,
      coherence,
      accuracy,
    };
  }

  private extractKeyElements(frame: CortexFrame): string[] {
    const elements: string[] = [];

    // Extract meaningful values from the frame
    const extractFromValue = (value: any): void => {
      if (typeof value === 'string' && value.length > 2) {
        elements.push(value);
      } else if (Array.isArray(value)) {
        value.forEach((item) => extractFromValue(item));
      } else if (typeof value === 'object' && value !== null) {
        Object.values(value).forEach((val) => extractFromValue(val));
      }
    };

    Object.values(frame).forEach((value) => extractFromValue(value));

    // Remove duplicates and filter
    return [...new Set(elements)].filter(
      (element) =>
        !['query', 'answer', 'event', 'state', 'entity', 'list'].includes(
          element.toLowerCase(),
        ),
    );
  }

  private assessFluency(text: string): number {
    // Simple fluency assessment based on sentence structure and length
    const sentences = text.split(/[.!?]+/).filter((s) => s.trim());
    if (sentences.length === 0) return 0;

    let score = 0.5; // Base score

    // Check average sentence length (ideal: 15-20 words)
    const avgWordsPerSentence = text.split(/\s+/).length / sentences.length;
    if (avgWordsPerSentence >= 10 && avgWordsPerSentence <= 25) {
      score += 0.2;
    }

    // Check for varied sentence structure
    const hasQuestions = text.includes('?');
    const hasExclamation = text.includes('!');
    if (hasQuestions || hasExclamation) {
      score += 0.1;
    }

    // Check for proper punctuation
    const punctuationRatio =
      (text.match(/[.!?]/g) || []).length / sentences.length;
    if (punctuationRatio >= 0.8) {
      score += 0.2;
    }

    return Math.min(1.0, score);
  }

  private assessCoherence(text: string): number {
    // Simple coherence assessment based on transition words and structure
    const transitionWords =
      /\b(however|therefore|thus|consequently|furthermore|moreover|in addition|also|but|although|because|since|while|when|if|then|so|and|or|but)\b/gi;
    const matches = text.match(transitionWords);

    let score = 0.4; // Base score

    if (matches) {
      score += Math.min(0.4, matches.length * 0.05);
    }

    // Check for logical flow
    const sentences = text.split(/[.!?]+/).filter((s) => s.trim());
    if (sentences.length > 1) {
      score += 0.2; // Multi-sentence texts tend to be more coherent
    }

    return Math.min(1.0, score);
  }

  private async assessAccuracy(
    text: string,
    request: CortexDecodingRequest,
  ): Promise<number> {
    try {
      // Multi-dimensional accuracy assessment
      const lexicalAccuracy = this.calculateLexicalAccuracy(
        request.cortexStructure,
        text,
      );
      const semanticAccuracy = await this.calculateSemanticAccuracy(
        request.cortexStructure,
        text,
      );
      const structuralAccuracy = this.calculateStructuralAccuracy(
        request.cortexStructure,
        text,
      );
      const contextualAccuracy = await this.calculateContextualAccuracy(
        request.cortexStructure,
        text,
        request,
      );

      // Weighted combination of accuracy metrics
      const overallAccuracy =
        lexicalAccuracy * 0.35 +
        semanticAccuracy * 0.35 +
        structuralAccuracy * 0.2 +
        contextualAccuracy * 0.1;

      // Apply format consistency bonus
      const formatConsistency = this.assessFormatConsistency(
        request.cortexStructure,
        text,
      );
      const finalAccuracy = Math.min(
        1.0,
        overallAccuracy + formatConsistency * 0.1,
      );

      // Apply penalty for hallucinations or irrelevant content
      const hallucinationPenalty = this.detectHallucinations(
        request.cortexStructure,
        text,
      );
      const adjustedAccuracy = Math.max(
        0.0,
        finalAccuracy - hallucinationPenalty,
      );

      this.logger.debug(
        `Accuracy scores: lexical=${lexicalAccuracy.toFixed(3)}, semantic=${semanticAccuracy.toFixed(3)}, structural=${structuralAccuracy.toFixed(3)}, contextual=${contextualAccuracy.toFixed(3)}, final=${adjustedAccuracy.toFixed(3)}`,
      );

      return adjustedAccuracy;
    } catch (error) {
      this.logger.warn('Failed to assess accuracy', error);
      return 0.5; // Default moderate accuracy
    }
  }

  // Fidelity calculation helpers
  private async calculateLexicalFidelity(
    originalFrame: CortexFrame,
    decodedText: string,
  ): Promise<number> {
    // Calculate how well lexical elements (words, terms) are preserved
    const originalWords = this.extractSignificantWords(originalFrame);
    const decodedWords = this.extractWordsFromText(decodedText);

    let matchedWords = 0;
    const matchedSet = new Set<string>();

    for (const originalWord of originalWords) {
      for (const decodedWord of decodedWords) {
        if (this.areWordsSimilar(originalWord, decodedWord)) {
          matchedWords++;
          matchedSet.add(originalWord);
          break;
        }
      }
    }

    const lexicalCoverage =
      originalWords.length > 0 ? matchedWords / originalWords.length : 1.0;

    // Bonus for exact matches
    let exactMatches = 0;
    for (const word of originalWords) {
      if (decodedWords.some((dw) => dw.toLowerCase() === word.toLowerCase())) {
        exactMatches++;
      }
    }

    const exactMatchBonus =
      (exactMatches / Math.max(originalWords.length, 1)) * 0.2;
    return Math.min(1.0, lexicalCoverage + exactMatchBonus);
  }

  private async calculateSemanticFidelity(
    originalFrame: CortexFrame,
    decodedText: string,
  ): Promise<number> {
    // Calculate semantic preservation using frame role relationships
    const frameRoles = Object.keys(originalFrame).filter(
      (key) => key !== 'frameType',
    );
    let semanticScore = 0;
    let roleCount = 0;

    for (const role of frameRoles) {
      const roleValue = (originalFrame as any)[role];
      if (typeof roleValue === 'string' && roleValue.length > 0) {
        const rolePresence = this.assessRolePresenceInText(
          role,
          roleValue,
          decodedText,
        );
        const roleRelevance = this.assessRoleSemanticRelevance(
          role,
          originalFrame,
        );
        semanticScore += rolePresence * roleRelevance;
        roleCount++;
      }
    }

    return roleCount > 0 ? Math.min(1.0, semanticScore / roleCount) : 0.8;
  }

  private calculateStructuralFidelity(
    originalFrame: CortexFrame,
    decodedText: string,
  ): number {
    // Assess how well the frame structure is reflected in the text
    const frameType = originalFrame.frameType;
    const roleCount = Object.keys(originalFrame).length - 1; // Exclude frameType

    // Check for frame type indication in text
    const frameTypeIndicator = this.detectFrameTypeInText(
      frameType,
      decodedText,
    );

    // Assess role distribution representation
    const roleDistributionScore = this.assessRoleDistributionInText(
      originalFrame,
      decodedText,
    );

    // Check for relational indicators
    const relationalIndicators = this.detectRelationalIndicators(
      originalFrame,
      decodedText,
    );

    return (
      frameTypeIndicator * 0.3 +
      roleDistributionScore * 0.4 +
      relationalIndicators * 0.3
    );
  }

  private async calculateContextualFidelity(
    originalFrame: CortexFrame,
    decodedText: string,
  ): Promise<number> {
    // Assess contextual appropriateness and coherence
    const coherenceScore = this.assessTextCoherence(decodedText);
    const contextualRelevance = this.assessContextualRelevance(
      originalFrame,
      decodedText,
    );
    const informationDensity = this.calculateInformationDensity(
      originalFrame,
      decodedText,
    );

    return (
      coherenceScore * 0.4 +
      contextualRelevance * 0.4 +
      informationDensity * 0.2
    );
  }

  private calculateLengthAppropriateness(
    originalFrame: CortexFrame,
    decodedText: string,
  ): number {
    // Assess if the decoded text length is appropriate for the frame complexity
    const frameComplexity = this.calculateFrameComplexity(originalFrame);
    const textLength = decodedText.trim().length;
    const wordsPerComplexity = Math.max(50, frameComplexity * 100); // Expected words

    const actualWords = decodedText.split(/\s+/).length;
    const ratio = actualWords / wordsPerComplexity;

    // Ideal ratio is between 0.5 and 2.0
    if (ratio >= 0.5 && ratio <= 2.0) return 1.0;
    if (ratio >= 0.25 && ratio <= 4.0) return 0.8;
    return 0.6; // Significant length mismatch
  }

  // Accuracy calculation helpers
  private calculateLexicalAccuracy(frame: CortexFrame, text: string): number {
    // Enhanced lexical accuracy with semantic understanding
    const frameContent = this.extractFrameContent(frame);
    const textWords = this.extractWordsFromText(text);

    let totalScore = 0;
    let elementCount = 0;

    for (const element of frameContent) {
      const elementScore = this.calculateElementAccuracy(element, textWords);
      totalScore += elementScore;
      elementCount++;
    }

    return elementCount > 0 ? totalScore / elementCount : 0.5;
  }

  private async calculateSemanticAccuracy(
    frame: CortexFrame,
    text: string,
  ): Promise<number> {
    // Assess semantic accuracy using role-based analysis
    const roles = Object.keys(frame).filter((key) => key !== 'frameType');
    let accuracySum = 0;
    let roleCount = 0;

    for (const role of roles) {
      const roleValue = (frame as any)[role];
      if (roleValue && typeof roleValue === 'string') {
        const roleAccuracy = this.assessRoleAccuracy(role, roleValue, text);
        const roleImportance = this.calculateRoleImportance(frame, role);

        accuracySum += roleAccuracy * roleImportance;
        roleCount++;
      }
    }

    return roleCount > 0 ? accuracySum / roleCount : 0.6;
  }

  private calculateStructuralAccuracy(
    frame: CortexFrame,
    text: string,
  ): number {
    // Assess how well the frame structure is represented
    const expectedStructure = this.inferExpectedStructure(frame);
    return this.measureStructureMatch(expectedStructure, text);
  }

  private async calculateContextualAccuracy(
    frame: CortexFrame,
    text: string,
    request: CortexDecodingRequest,
  ): Promise<number> {
    // Assess contextual accuracy considering the request context
    const domainRelevance = this.assessDomainRelevance(frame, text);
    const intentAlignment = this.assessIntentAlignment(frame, text, request);
    const audienceAppropriateness = this.assessAudienceAppropriateness(
      frame,
      text,
    );

    return (
      domainRelevance * 0.4 +
      intentAlignment * 0.4 +
      audienceAppropriateness * 0.2
    );
  }

  private assessFormatConsistency(frame: CortexFrame, text: string): number {
    // Assess if the text format is consistent with frame type
    const frameType = frame.frameType;
    let consistencyScore = 0.5;

    switch (frameType) {
      case 'query':
        consistencyScore = this.assessQueryFormatConsistency(text);
        break;
      case 'answer':
        consistencyScore = this.assessAnswerFormatConsistency(text);
        break;
      case 'event':
        consistencyScore = this.assessEventFormatConsistency(text);
        break;
      case 'list':
        consistencyScore = this.assessListFormatConsistency(text);
        break;
      default:
        consistencyScore = 0.6;
    }

    return consistencyScore;
  }

  private detectHallucinations(frame: CortexFrame, text: string): number {
    // Detect content not present in original frame
    const frameContent = JSON.stringify(frame).toLowerCase();
    const textWords = text.toLowerCase().split(/\s+/);

    let hallucinatedWords = 0;
    const stopWords = [
      'the',
      'a',
      'an',
      'and',
      'or',
      'but',
      'in',
      'on',
      'at',
      'to',
      'for',
      'of',
      'with',
      'by',
    ];

    for (const word of textWords) {
      if (
        word.length > 3 &&
        !stopWords.includes(word) &&
        !frameContent.includes(word)
      ) {
        hallucinatedWords++;
      }
    }

    // Penalty based on hallucinated content ratio
    const hallucinationRatio = hallucinatedWords / textWords.length;
    return Math.min(0.3, hallucinationRatio * 2); // Max penalty of 0.3
  }

  // Utility methods
  private extractSignificantWords(frame: CortexFrame): string[] {
    const words: string[] = [];
    const processedValues = new Set<string>();

    for (const [key, value] of Object.entries(frame)) {
      if (key === 'frameType') continue;

      if (typeof value === 'string' && value.length > 2) {
        const valueWords = value
          .toLowerCase()
          .split(/[^\w]+/)
          .filter(
            (word) =>
              word.length > 2 &&
              ![
                'the',
                'and',
                'or',
                'but',
                'in',
                'on',
                'at',
                'to',
                'for',
                'of',
              ].includes(word),
          );

        for (const word of valueWords) {
          if (!processedValues.has(word)) {
            words.push(word);
            processedValues.add(word);
          }
        }
      }
    }

    return words;
  }

  private extractWordsFromText(text: string): string[] {
    return text
      .toLowerCase()
      .split(/[^\w]+/)
      .filter((word) => word.length > 0);
  }

  private areWordsSimilar(word1: string, word2: string): boolean {
    // Simple similarity check - could be enhanced with stemming/lemmatization
    if (word1 === word2) return true;
    if (Math.abs(word1.length - word2.length) > 2) return false;

    // Check for common prefixes/suffixes
    const minLength = Math.min(word1.length, word2.length);
    const commonPrefix =
      word1.substring(0, minLength) === word2.substring(0, minLength);
    const levenshteinDistance = this.calculateLevenshteinDistance(word1, word2);

    return commonPrefix && levenshteinDistance <= 2;
  }

  private calculateLevenshteinDistance(str1: string, str2: string): number {
    const matrix = [];

    for (let i = 0; i <= str2.length; i++) {
      matrix[i] = [i];
    }

    for (let j = 0; j <= str1.length; j++) {
      matrix[0][j] = j;
    }

    for (let i = 1; i <= str2.length; i++) {
      for (let j = 1; j <= str1.length; j++) {
        if (str2.charAt(i - 1) === str1.charAt(j - 1)) {
          matrix[i][j] = matrix[i - 1][j - 1];
        } else {
          matrix[i][j] = Math.min(
            matrix[i - 1][j - 1] + 1, // substitution
            matrix[i][j - 1] + 1, // insertion
            matrix[i - 1][j] + 1, // deletion
          );
        }
      }
    }

    return matrix[str2.length][str1.length];
  }

  private assessRolePresenceInText(
    role: string,
    roleValue: string,
    text: string,
  ): number {
    const textLower = text.toLowerCase();
    const roleValueLower = roleValue.toLowerCase();

    // Direct inclusion check
    if (textLower.includes(roleValueLower)) return 1.0;

    // Partial match check
    const words = roleValueLower.split(/\s+/);
    let matchedWords = 0;
    for (const word of words) {
      if (word.length > 2 && textLower.includes(word)) {
        matchedWords++;
      }
    }

    return words.length > 0 ? matchedWords / words.length : 0.0;
  }

  private assessRoleSemanticRelevance(
    role: string,
    frame: CortexFrame,
  ): number {
    // Assess how semantically important this role is in the frame
    const frameType = frame.frameType;
    const requiredRoles = this.getRequiredRolesForFrameType(frameType);

    if (requiredRoles.includes(role)) return 1.0;

    // Check if this role provides unique information
    const roleValue = (frame as any)[role];
    if (typeof roleValue === 'string' && roleValue.length > 10) return 0.8;
    if (typeof roleValue === 'object') return 0.9;

    return 0.6; // Default moderate relevance
  }

  private detectFrameTypeInText(frameType: string, text: string): number {
    const textLower = text.toLowerCase();

    // Check for frame type indicators in text
    switch (frameType) {
      case 'query':
        return textLower.includes('what') ||
          textLower.includes('how') ||
          textLower.includes('?')
          ? 1.0
          : 0.3;
      case 'answer':
        return textLower.includes('answer') || textLower.includes('result')
          ? 0.8
          : 0.4;
      case 'event':
        return textLower.includes('happened') || textLower.includes('occurred')
          ? 0.9
          : 0.5;
      case 'list':
        return textLower.includes('list') || textLower.includes('items')
          ? 0.8
          : 0.4;
      default:
        return 0.6;
    }
  }

  private assessRoleDistributionInText(
    frame: CortexFrame,
    text: string,
  ): number {
    const roles = Object.keys(frame).filter((key) => key !== 'frameType');
    const textWords = text.toLowerCase().split(/\s+/);

    let representedRoles = 0;
    for (const role of roles) {
      const roleValue = (frame as any)[role];
      if (typeof roleValue === 'string') {
        const roleWords = roleValue.toLowerCase().split(/\s+/);
        const hasRoleWords = roleWords.some(
          (word) => word.length > 2 && textWords.includes(word),
        );
        if (hasRoleWords) representedRoles++;
      }
    }

    return roles.length > 0 ? representedRoles / roles.length : 0.5;
  }

  private detectRelationalIndicators(frame: CortexFrame, text: string): number {
    // Check for relational words that indicate frame structure
    const relationalWords = [
      'and',
      'or',
      'but',
      'because',
      'therefore',
      'however',
      'although',
      'while',
      'when',
      'where',
      'who',
      'which',
    ];
    const textWords = text.toLowerCase().split(/\s+/);

    let relationalMatches = 0;
    for (const word of relationalWords) {
      if (textWords.includes(word)) relationalMatches++;
    }

    return Math.min(1.0, relationalMatches / 5); // Normalize to max 5 relational words
  }

  private assessTextCoherence(text: string): number {
    // Assess text coherence and flow
    const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);

    if (sentences.length === 0) return 0.0;

    let coherenceScore = 0.5; // Base coherence

    // Sentence length consistency
    const avgSentenceLength =
      sentences.reduce((sum, s) => sum + s.split(/\s+/).length, 0) /
      sentences.length;
    const lengthVariance =
      sentences.reduce((sum, s) => {
        const diff = s.split(/\s+/).length - avgSentenceLength;
        return sum + diff * diff;
      }, 0) / sentences.length;

    if (lengthVariance < 50) coherenceScore += 0.2;

    // Transition word usage
    const transitionWords = [
      'however',
      'therefore',
      'moreover',
      'furthermore',
      'consequently',
      'similarly',
      'likewise',
    ];
    const transitionCount = transitionWords.reduce(
      (count, word) => count + (text.toLowerCase().includes(word) ? 1 : 0),
      0,
    );

    coherenceScore += Math.min(0.3, transitionCount * 0.1);

    return Math.min(1.0, coherenceScore);
  }

  private assessContextualRelevance(frame: CortexFrame, text: string): number {
    // Assess if the text content is contextually relevant to the frame
    const frameContent = JSON.stringify(frame).toLowerCase();
    const textLower = text.toLowerCase();

    // Calculate content overlap
    const frameWords = frameContent
      .split(/\s+/)
      .filter((word) => word.length > 3);
    const textWords = textLower.split(/\s+/);

    let relevantWords = 0;
    for (const word of frameWords.slice(0, 20)) {
      // Check first 20 significant words
      if (textWords.includes(word)) relevantWords++;
    }

    const relevanceScore =
      frameWords.length > 0
        ? relevantWords / Math.min(frameWords.length, 20)
        : 0.5;

    // Bonus for semantic coherence
    const semanticCoherence = this.calculateSemanticCoherence(frame, text);
    return Math.min(1.0, relevanceScore + semanticCoherence * 0.2);
  }

  private calculateInformationDensity(
    frame: CortexFrame,
    text: string,
  ): number {
    // Calculate information density ratio
    const frameInfoUnits = this.countInformationUnits(frame);
    const textInfoUnits = this.countInformationUnitsInText(text);

    if (frameInfoUnits === 0) return 0.5;

    const densityRatio = textInfoUnits / frameInfoUnits;

    // Ideal density ratio is around 1.0
    if (densityRatio >= 0.8 && densityRatio <= 1.2) return 1.0;
    if (densityRatio >= 0.5 && densityRatio <= 2.0) return 0.8;
    return 0.6;
  }

  private calculateFrameComplexity(frame: CortexFrame): number {
    let complexity = 1;

    complexity += Object.keys(frame).length * 0.5; // More roles = more complex

    for (const value of Object.values(frame)) {
      if (typeof value === 'object' && value !== null) {
        complexity += 1;
        if (Array.isArray(value)) {
          complexity += value.length * 0.2;
        }
      }
      if (typeof value === 'string' && value.length > 100) {
        complexity += 0.5; // Long strings increase complexity
      }
    }

    return complexity;
  }

  private extractFrameContent(frame: CortexFrame): string[] {
    const content: string[] = [];

    for (const [key, value] of Object.entries(frame)) {
      if (key === 'frameType') continue;

      if (typeof value === 'string') {
        content.push(value);
      } else if (Array.isArray(value)) {
        content.push(...value.filter((item) => typeof item === 'string'));
      }
    }

    return content;
  }

  private calculateElementAccuracy(
    element: string,
    textWords: string[],
  ): number {
    if (!element || element.length < 3) return 0.5;

    const elementWords = element.toLowerCase().split(/\s+/);
    let matchedWords = 0;

    for (const word of elementWords) {
      if (textWords.includes(word.toLowerCase())) {
        matchedWords++;
      }
    }

    return elementWords.length > 0 ? matchedWords / elementWords.length : 0.5;
  }

  private assessRoleAccuracy(
    role: string,
    roleValue: string,
    text: string,
  ): number {
    const textLower = text.toLowerCase();
    const roleValueLower = roleValue.toLowerCase();

    // Exact match
    if (textLower.includes(roleValueLower)) return 1.0;

    // Partial word matches
    const roleWords = roleValueLower
      .split(/\s+/)
      .filter((word) => word.length > 2);
    const textWords = textLower.split(/\s+/);

    let matchedWords = 0;
    for (const word of roleWords) {
      if (textWords.some((tw) => this.areWordsSimilar(word, tw))) {
        matchedWords++;
      }
    }

    return roleWords.length > 0 ? matchedWords / roleWords.length : 0.5;
  }

  private calculateRoleImportance(frame: CortexFrame, role: string): number {
    const frameType = frame.frameType;
    const requiredRoles = this.getRequiredRolesForFrameType(frameType);

    if (requiredRoles.includes(role)) return 1.0;

    const roleValue = (frame as any)[role];
    if (typeof roleValue === 'object') return 0.9;
    if (typeof roleValue === 'string' && roleValue.length > 20) return 0.8;

    return 0.6;
  }

  private inferExpectedStructure(frame: CortexFrame): any {
    const frameType = frame.frameType;
    const roles = Object.keys(frame).filter((key) => key !== 'frameType');

    return {
      frameType,
      roleCount: roles.length,
      hasComplexRoles: roles.some(
        (role) => typeof (frame as any)[role] === 'object',
      ),
      primaryRoles: this.getRequiredRolesForFrameType(frameType),
    };
  }

  private measureStructureMatch(expectedStructure: any, text: string): number {
    let matchScore = 0.5;

    // Check frame type representation
    const frameTypeWords = expectedStructure.frameType.split(/[^\w]+/);
    const hasFrameTypeWords = frameTypeWords.some((word: string) =>
      text.toLowerCase().includes(word.toLowerCase()),
    );
    if (hasFrameTypeWords) matchScore += 0.2;

    // Check role count appropriateness
    const textLength = text.split(/\s+/).length;
    const expectedLength = expectedStructure.roleCount * 15; // Rough estimate
    const lengthRatio = textLength / expectedLength;

    if (lengthRatio >= 0.5 && lengthRatio <= 2.0) matchScore += 0.2;

    // Check for complex structure indicators
    if (expectedStructure.hasComplexRoles) {
      const complexityIndicators = [
        'including',
        'with',
        'having',
        'containing',
      ];
      const hasComplexityIndicators = complexityIndicators.some((indicator) =>
        text.toLowerCase().includes(indicator),
      );
      if (hasComplexityIndicators) matchScore += 0.1;
    }

    return Math.min(1.0, matchScore);
  }

  private assessDomainRelevance(frame: CortexFrame, text: string): number {
    // Assess if the text content is relevant to the frame's domain
    const frameContent = JSON.stringify(frame).toLowerCase();
    const textLower = text.toLowerCase();

    // Extract domain-specific terms from frame
    const domainTerms = this.extractDomainTerms(frameContent);

    let relevantTerms = 0;
    for (const term of domainTerms) {
      if (textLower.includes(term)) relevantTerms++;
    }

    return domainTerms.length > 0 ? relevantTerms / domainTerms.length : 0.6;
  }

  private assessIntentAlignment(
    frame: CortexFrame,
    text: string,
    request: CortexDecodingRequest,
  ): number {
    // Assess if the text aligns with the intended purpose
    const frameType = frame.frameType;
    let alignmentScore = 0.6;

    // Check for intent-specific indicators
    switch (frameType) {
      case 'query':
        alignmentScore = this.assessQueryIntentAlignment(text);
        break;
      case 'answer':
        alignmentScore = this.assessAnswerIntentAlignment(text);
        break;
      case 'event':
        alignmentScore = this.assessEventIntentAlignment(text);
        break;
      case 'list':
        alignmentScore = this.assessListIntentAlignment(text);
        break;
    }

    return alignmentScore;
  }

  private assessAudienceAppropriateness(
    frame: CortexFrame,
    text: string,
  ): number {
    // Assess if the text is appropriate for the intended audience
    const textComplexity = this.calculateTextComplexity(text);
    const frameComplexity = this.calculateFrameComplexity(frame);

    // Audience appropriateness based on complexity matching
    const complexityDiff = Math.abs(textComplexity - frameComplexity);

    if (complexityDiff <= 1) return 1.0;
    if (complexityDiff <= 2) return 0.8;
    return 0.6;
  }

  // Format consistency assessment methods
  private assessQueryFormatConsistency(text: string): number {
    const indicators = ['?', 'what', 'how', 'why', 'when', 'where', 'who'];
    const textLower = text.toLowerCase();

    const indicatorCount = indicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.5 + indicatorCount * 0.1);
  }

  private assessAnswerFormatConsistency(text: string): number {
    const indicators = [
      'answer',
      'result',
      'solution',
      'response',
      'because',
      'therefore',
    ];
    const textLower = text.toLowerCase();

    const indicatorCount = indicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.5 + indicatorCount * 0.08);
  }

  private assessEventFormatConsistency(text: string): number {
    const indicators = [
      'happened',
      'occurred',
      'took place',
      'was',
      'were',
      'when',
    ];
    const textLower = text.toLowerCase();

    const indicatorCount = indicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.5 + indicatorCount * 0.08);
  }

  private assessListFormatConsistency(text: string): number {
    // Check for list-like structures
    const lines = text.split('\n');
    const bulletLines = lines.filter(
      (line) => line.trim().match(/^[-*•]\s/) || line.trim().match(/^\d+\.\s/),
    );

    const listRatio = bulletLines.length / lines.length;
    return Math.min(1.0, 0.4 + listRatio * 2);
  }

  // Utility methods
  private getRequiredRolesForFrameType(frameType: string): string[] {
    const requiredRolesMap: Record<string, string[]> = {
      query: ['action'],
      answer: ['content'],
      event: ['action', 'time'],
      state: ['entity', 'value'],
      entity: ['name'],
      list: ['items'],
    };

    return requiredRolesMap[frameType] || [];
  }

  private calculateSemanticCoherence(frame: CortexFrame, text: string): number {
    // Calculate semantic coherence between frame and text
    const frameConcepts = this.extractConceptsFromFrame(frame);
    const textConcepts = this.extractConceptsFromText(text);

    let coherenceScore = 0;
    for (const concept of frameConcepts) {
      if (textConcepts.some((tc) => this.areConceptsRelated(concept, tc))) {
        coherenceScore += 0.1;
      }
    }

    return Math.min(1.0, coherenceScore);
  }

  private countInformationUnits(frame: CortexFrame): number {
    let units = 0;

    for (const [key, value] of Object.entries(frame)) {
      if (key === 'frameType') continue;

      if (typeof value === 'string') {
        units += Math.ceil(value.length / 50); // Roughly 50 chars per info unit
      } else if (Array.isArray(value)) {
        units += value.length;
      } else if (typeof value === 'object') {
        units += Object.keys(value).length;
      }
    }

    return units;
  }

  private countInformationUnitsInText(text: string): number {
    const words = text.split(/\s+/).filter((word) => word.length > 0);
    return Math.ceil(words.length / 10); // Roughly 10 words per info unit
  }

  private extractDomainTerms(content: string): string[] {
    const words = content
      .split(/\s+/)
      .filter(
        (word) =>
          word.length > 4 &&
          ![
            'frameType',
            'true',
            'false',
            'null',
            'string',
            'number',
            'object',
          ].includes(word) &&
          !word.match(/^\d+$/),
      );

    return [...new Set(words)].slice(0, 15);
  }

  private calculateTextComplexity(text: string): number {
    const words = text.split(/\s+/);
    const avgWordLength =
      words.reduce((sum, word) => sum + word.length, 0) / words.length;
    const uniqueWords = new Set(words.map((w) => w.toLowerCase())).size;
    const lexicalDiversity = uniqueWords / words.length;

    return (
      avgWordLength * 0.3 +
      lexicalDiversity * 10 * 0.4 +
      (words.length / 100) * 0.3
    );
  }

  // Intent alignment assessment methods
  private assessQueryIntentAlignment(text: string): number {
    const queryIndicators = [
      '?',
      'what',
      'how',
      'why',
      'when',
      'where',
      'who',
      'which',
    ];
    const textLower = text.toLowerCase();

    const indicatorCount = queryIndicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.4 + indicatorCount * 0.15);
  }

  private assessAnswerIntentAlignment(text: string): number {
    const answerIndicators = [
      'answer',
      'because',
      'therefore',
      'result',
      'solution',
      'is',
    ];
    const textLower = text.toLowerCase();

    const indicatorCount = answerIndicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.5 + indicatorCount * 0.1);
  }

  private assessEventIntentAlignment(text: string): number {
    const eventIndicators = [
      'happened',
      'occurred',
      'was',
      'were',
      'took place',
      'at',
    ];
    const textLower = text.toLowerCase();

    const indicatorCount = eventIndicators.reduce(
      (count, indicator) => count + (textLower.includes(indicator) ? 1 : 0),
      0,
    );

    return Math.min(1.0, 0.5 + indicatorCount * 0.1);
  }

  private assessListIntentAlignment(text: string): number {
    const lines = text.split('\n');
    const structuredLines = lines.filter(
      (line) => line.trim().match(/^[-*•]\s/) || line.trim().match(/^\d+\.\s/),
    );

    return Math.min(1.0, 0.3 + (structuredLines.length / lines.length) * 1.2);
  }

  private extractConceptsFromFrame(frame: CortexFrame): string[] {
    const concepts: string[] = [];

    for (const [key, value] of Object.entries(frame)) {
      if (key === 'frameType') continue;

      if (typeof value === 'string') {
        // Extract noun phrases as concepts
        const words = value.split(/\s+/);
        for (let i = 0; i < words.length - 1; i++) {
          if (words[i].length > 3 && words[i + 1].length > 3) {
            concepts.push(`${words[i]} ${words[i + 1]}`);
          }
        }
      }
    }

    return [...new Set(concepts)].slice(0, 10);
  }

  private extractConceptsFromText(text: string): string[] {
    const concepts: string[] = [];
    const words = text.split(/\s+/);

    for (let i = 0; i < words.length - 1; i++) {
      if (words[i].length > 3 && words[i + 1].length > 3) {
        concepts.push(`${words[i]} ${words[i + 1]}`.toLowerCase());
      }
    }

    return [...new Set(concepts)].slice(0, 10);
  }

  private areConceptsRelated(concept1: string, concept2: string): boolean {
    const words1 = concept1.toLowerCase().split(/\s+/);
    const words2 = concept2.toLowerCase().split(/\s+/);

    // Check for word overlap
    return words1.some((word) => words2.includes(word));
  }

  private assessTextQuality(text: string): number {
    // Overall text quality assessment
    if (text.length < 10) return 0.2;
    if (text.length > 10000) return 0.7; // Very long texts might be over-generated

    // Check for repetitive patterns
    const words = text.split(/\s+/);
    const uniqueWords = new Set(words);
    const uniquenessRatio = uniqueWords.size / words.length;

    return Math.min(1.0, uniquenessRatio * 1.2);
  }

  private generateCacheKey(request: CortexDecodingRequest): string {
    return `${JSON.stringify(request.cortexStructure)}_${request.targetLanguage}_${request.style}_${JSON.stringify(request.options)}`;
  }

  private generateSemanticHash(frame: CortexFrame): string {
    const content = JSON.stringify(frame);
    let hash = 0;
    for (let i = 0; i < content.length; i++) {
      const char = content.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return hash.toString(36);
  }

  private postProcessDecodedText(
    text: string,
    request: CortexDecodingRequest,
  ): string {
    let processed = text;

    // Apply formatting based on request
    if (request.format === 'markdown') {
      processed = this.convertToMarkdown(processed);
    } else if ((request.format as string) === 'html') {
      processed = this.convertToHtml(processed);
    }

    // Apply readability enhancements
    if (request.options?.enhanceReadability) {
      processed = this.enhanceReadability(processed);
    }

    // Apply length constraints
    if (request.options?.maxLength) {
      processed = this.truncateToLength(processed, request.options.maxLength);
    }

    return processed;
  }

  private convertToMarkdown(text: string): string {
    // Convert plain text to markdown format
    let markdown = text;

    // Convert headers (simple heuristic)
    markdown = markdown.replace(/^([A-Z][^.!?]*)$/gm, '# $1');

    // Convert lists
    markdown = markdown.replace(/^(\d+)\.\s+/gm, '$1. ');

    // Convert bullet points
    markdown = markdown.replace(/^[-*]\s+/gm, '- ');

    return markdown;
  }

  private convertToHtml(text: string): string {
    // Convert to basic HTML
    let html = text;

    // Convert line breaks
    html = html.replace(/\n\n/g, '</p><p>');
    html = html.replace(/\n/g, '<br>');

    // Wrap in paragraphs
    html = `<p>${html}</p>`;

    return html;
  }

  private enhanceReadability(text: string): string {
    let enhanced = text;

    // Add paragraph breaks
    enhanced = enhanced.replace(/([.!?])\s+(?=[A-Z])/g, '$1\n\n');

    // Fix spacing issues
    enhanced = enhanced.replace(/\s+/g, ' ');
    enhanced = enhanced.replace(/\s*\n\s*/g, '\n');

    // Capitalize sentence starts
    enhanced = enhanced.replace(
      /(^|[.!?]\s*)([a-z])/g,
      (match, separator, letter) => separator + letter.toUpperCase(),
    );

    return enhanced;
  }

  private truncateToLength(text: string, maxLength: number): string {
    if (text.length <= maxLength) return text;

    // Find a good break point
    let truncated = text.substring(0, maxLength);
    const lastSentenceEnd = Math.max(
      truncated.lastIndexOf('.'),
      truncated.lastIndexOf('!'),
      truncated.lastIndexOf('?'),
    );

    if (lastSentenceEnd > maxLength * 0.8) {
      truncated = truncated.substring(0, lastSentenceEnd + 1);
    }

    return truncated + '...';
  }

  private getPostProcessingSteps(request: CortexDecodingRequest): string[] {
    const steps: string[] = [];

    if (request.format) steps.push(`format_${request.format}`);
    if (request.options?.enhanceReadability)
      steps.push('readability_enhancement');
    if (request.options?.maxLength) steps.push('length_truncation');

    return steps;
  }
}
