# Simplified OpenTelemetry Collector Configuration for Testing
# This is a minimal configuration to get started quickly

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1024
    timeout: 200ms

exporters:
  logging:
    loglevel: info
    sampling_initial: 10
    sampling_thereafter: 100
    
  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: costkatana

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, pprof]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
      
  telemetry:
    logs:
      level: info
