# Prometheus configuration for Cost Katana observability
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cost-katana'
    environment: 'development'

# Alert manager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Scrape OTel Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:9464']
        labels:
          service: 'otel-collector'
    metric_relabel_configs:
      # Keep only important metrics
      - source_labels: [__name__]
        regex: 'costkatana_.*|gen_ai_.*|http_server_.*|business_.*|up|.*_duration_.*|.*_count|.*_total'
        action: keep

  # Scrape Node.js application metrics (if exposed)
  - job_name: 'cost-katana-api'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'cost-katana-api'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Optional: Scrape Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'node-exporter'

# Remote write configuration (for sending to external systems)
# remote_write:
#   - url: 'https://prometheus-endpoint.example.com/api/v1/write'
#     bearer_token: 'YOUR_TOKEN_HERE'
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'costkatana_.*|gen_ai_.*'
#         action: keep
